version: '3.1'

services:
    php:
        image: php:7.4-apache
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html/

    sqlite3:
        image: nouchka/sqlite3:latest
        stdin_open: true
        tty: true
        volumes:
            - ./src/config:/root
